"""init database version for one user

Revision ID: 56bfeb296f17
Revises: 
Create Date: 2023-08-29 13:50:25.631757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56bfeb296f17'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Category',
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_base_expanse', sa.Boolean(), nullable=False),
    sa.Column('aliases', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('codename')
    )
    op.create_table('User',
    sa.Column('codename', sa.String(length=255), nullable=False),
    sa.Column('daily_limit', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('codename')
    )
    op.create_table('Expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('category_codename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['category_codename'], ['Category.codename'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Expense')
    op.drop_table('User')
    op.drop_table('Category')
    # ### end Alembic commands ###
